crab.up();
crab.place('41', 0);
crab.placeDown('41', 0);
crab.back();
crab.place('41', 0);
crab.placeDown('41', 0);
crab.up();
crab.placeDown('41', 0);
crab.up();
crab.placeDown('41', 0);
crab.place('41', 0);
crab.up();
crab.placeDown('41', 0);
